# https://api.github.com/repositories/303967701/contents/sparql-anything-it/src/test/resources/issues/issue175-2.sparql?ref=23626c6522e626253fd88da4a8674fd46004d205
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX fx: <http://sparql.xyz/facade-x/ns/>
select *
WHERE {
SERVICE <x-sparql-anything:> {
fx:properties fx:location "https://sparql-anything.cc/example1.json" .
?s ?p ?o.
}
}