# https://api.github.com/repositories/598502070/contents/append/count-triples.sparql?ref=53dcc5377587eb7f804ed54c9be1acb3dc26a434
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX fx:  <http://sparql.xyz/facade-x/ns/>

select count(*)
where {
	service <x-sparql-anything:> {
		fx:properties fx:location "./out.ttl" .		
		?a ?b ?c
	}
}